wallpaper {
  monitor = HDMI-A-1
  path = ~/.config/simple-linux/files/wallpaper.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-1
  path = ~/.config/simple-linux/files/wallpaper.png
  fit_mode = cover
}

splash = false
ipc = false
