listener {
  timeout = 150
  on-timeout = brightnessctl -s set 10
  on-resume = brightnessctl -r
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener {
  timeout = 150
  on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
  on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
  timeout = 300
  on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 400
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
